config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources:users,only: [:show] do
  	resources:friendships,only: [:create,:destroy]
  end
  resources:posts do
  	resources:comments,only: [:new,:create,:show,:index,:destroy]
  	resources:likes,only: [:create]
  end
  get '/my_friends', to: 'users#myfriends'
  get '/search_friend', to: 'users#search'
  get 'friendship_search',to: 'friendships#search',as: 'friendship_search'
  get 'users/:id/friendrequest', to:'friendships#friendrequest',as: 'user_friendrequests'
  post 'users/:id/friendrequest', to:'friendships#accept'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
	belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
		@post=Post.find(params[:post_id])
		@comment=Comment.new(post_id:@post)
	end

	def create
		@post=Post.find(params[:post_id])
		@comment=Comment.new(comment_params)
		@comment.user=current_user
		@comment.post=@post
		@post.comments_count=@post.comments_count+1
		if @comment.save && @post.save
			flash[:notice]="Comment Successfully Created"
			redirect_to post_comments_path(@post)
		else
			render 'new'
		end
	end
	def index
		@post=Post.find(params[:post_id])
		@comments=@post.comments.all
	end
	def destroy
		@post=Post.find(params[:post_id])
		@comment=Comment.find(params[:id])
		@comment.destroy
		redirect_to @post
	end

	private
	def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.erb
<h3>All comments on post id:<%= @post.id %></h3>
<% @comments.each do |current_comment| %>
	<p> 
		Comment_by_User <%= current_comment.user.id %>  <%=current_comment.content %>
		<% if can? :destroy,current_comment %>
			<%= link_to 'Delete Comment',post_comment_path(@post,current_comment),method: :delete %>
		<% end %>
	</p>
<% end %>

app/views/comments/new.html.erb
<h1>Comment create karo</h1>
<%= form_with(scope: :comment,url: post_comments_path ,local: true) do |f| %>


  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="actions">
    <%= f.submit "add comment" %>
  </div>
<% end %>