config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources:users,only: [:show] do
  	resources:friendships,only: [:create,:destroy]
  end
  resources:posts do
  	resources:comments,only: [:new,:create,:show,:index,:destroy]
  	resources:likes,only: [:create]
  end
  get '/my_friends', to: 'users#myfriends'
  get '/search_friend', to: 'users#search'
  get 'friendship_search',to: 'friendships#search',as: 'friendship_search'
  get 'users/:id/friendrequest', to:'friendships#friendrequest',as: 'user_friendrequests'
  post 'users/:id/friendrequest', to:'friendships#accept'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :fname ,presence: true,length: { minimum: 3,maximum: 25}
  validates :lname ,presence: true,length: { minimum: 3,maximum: 25}
  validates :acc_status,presence: true,:inclusion => { :in => 0..2 }
  has_many :friend_sent , class_name: 'Friendship' ,foreign_key: 'sender_id',inverse_of: 'sender',dependent: :destroy
  has_many :friends, -> {  Friendship.friends },through: :friend_sent,source: :receiver
  has_many :friend_received ,class_name: 'Friendship',foreign_key: 'receiver_id',inverse_of: 'receiver',dependent: :destroy
  has_many :friendsrec, -> { Friendship.friends },through: :friend_received,source: :sender
  has_many :friend_request, -> { Friendship. not_friends },through: :friend_received,source: :sender
  has_many :posts,dependent: :destroy
  has_many :likes,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_one_attached :image

  def full_name
    "#{fname} #{lname}"
  end

  def all_friends
    (friends+friendsrec).uniq
  end
  def self.search(searchstring,reject_id)
  	searchstring.strip!
  	#@first=match('email',searchstring)
  	#@second=match('fname',searchstring)
  	#@third=match('lname',searchstring)
    #(@first+@second+@third).uniq
    @allsearchresult=where("email like ?","%#{searchstring}%").or(where("fname like ?","%#{searchstring}%").or(where("lname like ?","%#{searchstring}%")))
    @allsearchresult=@allsearchresult.where.not(id:reject_id)
  	@allsearchresult
  end

  def self.match(fieldname,searchstring)
  	where("#{fieldname} like ?","%#{searchstring}%")
  end
  def except_current_user(users)
  	users.reject { |user| user.id==self.id }
  end
  def not_friends_with?(id_of_friend)
    @ff=Friendship.where(receiver_id:self.id,sender_id:id_of_friend,status: true).or(Friendship.where(receiver_id:id_of_friend,sender_id:self.id,status: true))
    !@ff.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def myfriends
		@friends=current_user.all_friends
	end
	def show
		@user=User.find(params[:id])
		@friendsrequest=@user.friend_request
  end
  def search
    
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_result.html.erb
<% if @friends %>
	<% @friends.each do |friend| %>
		<p>Name:<%= friend.full_name %> email:<%= friend.email %>
		 		SendFriendRequest:<%= link_to 'Send',user_friendships_path(friend),method: :post  %>		
		</p>
	<% end %>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/myfriends.html.erb
<h1>All friends</h1>

<% @friends.each do |current_friend| %>
	<p> Friend name : <%= current_friend.full_name %>Remove:<%= link_to 'RemoveFriend' ,user_friendship_path(current_user,current_friend),method: :delete %>  </p>
<% end %>

app/views/users/search.html.erb
<div class='search-area'>
	<h3>Search Friend</h3>
	<%= form_tag friendship_search_path,remote: true,method: :get do %>
		<div class="form-group row">
			<div class="col-sm-9">
				<%= text_field_tag :friend,params[:friend],placeholder: "Search Friend",autofocus: true, class: "form-control form-control-lg" %>
			</div>
			<div class="col-sm-3">
				<%= button_tag type: :submit ,class:"btn btn-success" do %>
					<%= 'Search' %>
				<% end %>
			</div>
		</div>
		<% end %>
</div>

<div id="results">
	<%= render 'users/result' %>
</div>

app/views/users/show.html.erb
<h1> This is <%= @user.full_name %> show page </h1>
<% if @user.id != current_user.id %>
	<p> this user is not current user</p>
	<p>Name:<%= @user.full_name %> Email:<%= @user.email %></p>
	<% if @user.image.present? %>
		<div style="width:400px;height:auto">
			<%= image_tag(@user.image,style: 'width:100%') %>
		</div>
	<% end %>
	<% if current_user.not_friends_with?(@user.id) %>
		<%= link_to 'Send Friend request', user_friendships_path(@user),method: :post %>
	<% end %>
<% else %>
	<p>Name:<%= @user.full_name %> Email:<%= @user.email %></p>
	<% if @user.image.present? %>
		<div style="width:400px;height:auto">
			<%= image_tag(@user.image,style: 'width:100%') %>
		</div>
	<% end %>
<% end %>