config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources:users,only: [:show] do
  	resources:friendships,only: [:create,:destroy]
  end
  resources:posts do
  	resources:comments,only: [:new,:create,:show,:index,:destroy]
  	resources:likes,only: [:create]
  end
  get '/my_friends', to: 'users#myfriends'
  get '/search_friend', to: 'users#search'
  get 'friendship_search',to: 'friendships#search',as: 'friendship_search'
  get 'users/:id/friendrequest', to:'friendships#friendrequest',as: 'user_friendrequests'
  post 'users/:id/friendrequest', to:'friendships#accept'
end

app/models/post.rb
class Post < ApplicationRecord
	enum status: { Public: 0, Private:1,Friend:2 }
  belongs_to :user
	has_many :likes,dependent: :destroy
	has_many :comments,dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
		@posts=current_user.posts
		@friends=current_user.all_friends
		@friends.each do|current_friend|
			@posts+= current_friend.posts.where(status:"Public").or(current_friend.posts.where(status:"Friend")) 
		end
	end
	def new
		@post=Post.new
	end
	def show
		@post=Post.find(params[:id])
		authorize! :read,@post
	end
	def create
		@post = Post.new(post_params) 
    @post.user = current_user
    if @post.save 
      flash[:notice] = "Post was created successfully." 
      redirect_to @post
    else 
      render 'new' 
    end

	end
	def edit
		@post=Post.find(params[:id])
		authorize! :update, @post
	end

	def update
		@post=Post.find(params[:id])
		@post.update(post_params)
		redirect_to @post
	end
	def destroy
		@post=Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
    params.require(:post).permit(:description,:status)
   end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description, autofocus: true, autocomplete: "description" %>
  </div>
  <div class="field">
  	<%= f.select :status, ["Public", "Private", "Friend"] %>
  </div>
  <div class="actions">
    <%= f.submit "submit" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit your Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Timeline</h1>
<% if @posts %>
	<% @posts.each do |p| %>
   	<p>Created_by: <%=p.user.full_name %> content <%= p.description %>
   			<% if can? :update,p %>
    			  <%=link_to 'Edit Post',edit_post_path(p) %>
   			<% end %>
   			<% if can? :destroy,p %>  
    			<%= link_to 'Delete',post_path(p),method: :delete,data: {confirm: "are you sure"} %>
    		<% end %>
    		<%= link_to 'Show',post_path(p) %>
  	  </p>
  <% end %>
<% end %>
<br>

app/views/posts/new.html.erb
<h1>Create Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Post show page </h1>
<p><%= @post.description %></p>
<p><%= @post.user_id %>
<br>
<p>Total comments: <%= @post.comments.count %> Total Likes: <%= @post.likes.count %> <%= link_to 'Create comment',
new_post_comment_path(@post) %> <%= link_to 'Like', post_likes_path(@post),method: :POST %>
	<%= link_to 'Show all comments',post_comments_path(@post) %>
</p>
<br>

<br>
<% if can? :destroy,@post %>
	<%= link_to "delete_post", post_path, method: :delete, data: {confirm: "are you sure"} %>
<% end %>